# Chapter-32

#### -> Loading Dataset from CSV

In [25]:
import pandas as pd
data=pd.read_csv("student_scores.csv")
display(data.head(5))
print("\nColumns:",data.columns.tolist())
print("\nInfo:")
print(data.info())
print("\nDescribe:")
display(data.describe())

     name  hours  score gender grades class
0   Aarav      8     76      M      A    9A
1    Riya      5     62      F      B    9B
2   Kabir     10     88      M      A   10A
3    Sana      4     55      F      C    9A
4  Vivaan      7     72      M      B   10B

Columns: ['name', 'hours', 'score', 'gender', 'grades', 'class']

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    92 non-null     object
 1   hours   92 non-null     int64
 2   score   92 non-null     int64
 3   gender  92 non-null     object
 4   grades  92 non-null     object
 5   class   92 non-null     object
dtypes: int64(2), object(4)
memory usage: 4.4+ KB
None

Describe:

           hours      score
count  92.000000  92.000000
mean    6.510870  68.836957
std     2.265336  15.692286
min     2.000000  35.000000
25%     5.000000  57.000000
50%     7.000000  70.000000
75%     8.000000  82.000000
max    11.000000  94.000000

#### -> Data Preprocessing

In [26]:
print(data.isnull().sum())

# Option 1
data["score"]=data["score"].fillna(data["score"].mean())

# Option 2
data=data.dropna()

name      0
hours     0
score     0
gender    0
grades    0
class     0
dtype: int64

In [57]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["gender"]=le.fit_transform(data["gender"])
print(data.head(5))
data["class_en"]=le.fit_transform(data["grades"])

     name  hours  score  gender grades class  class_en
0   Aarav      8     76       1      A    9A         0
1    Riya      5     62       0      B    9B         1
2   Kabir     10     88       1      A   10A         0
3    Sana      4     55       0      C    9A         2
4  Vivaan      7     72       1      B   10B         1

#### -> Input / Output Selection

In [29]:
x=data[["hours","class_en"]]
y=data["score"]

#### -> Spliting the Entire Data into Train Data & Test Data

In [52]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)
print(x_train.head(5))

    hours  class_en
30      5         2
33      7         1
11      7         1
66      5         2
69      4         2

#### -> Normalization

In [58]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train_scaled=sc.fit_transform(x_train)
x_test_scaled=sc.transform(x_test)

In [63]:
print("X_train Shape:",x_train.shape)
print("X_test Shape:",x_test.shape)
print("Y_train Shape:",y_train.shape)
print("Y_test Shape:",y_test.shape)
print("Mean:",x_train_scaled.mean(axis=0))
print("Std:",x_train_scaled.std(axis=0))

X_train Shape: (69, 2)
X_test Shape: (23, 2)
Y_train Shape: (69,)
Y_test Shape: (23,)
Mean: [2.89623398e-17 3.53984153e-17]
Std: [1. 1.]